[package]
name = "screen"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
license = "MIT OR Apache-2.0"
description = "STM32F407 ILI9341 LCD Display with Embassy and FMC"

[dependencies]
embassy-stm32 = { version = "0.4.0", features = ["defmt", "unstable-pac", "memory-x", "time-driver-any", "exti"] }
display-interface = { version = "0.5.0", default-features = false }
defmt = "1.0.1"
defmt-rtt = "1.1.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.5"
embedded-hal = "1.0.0"
ili9341 = "0.6.0"
embedded-graphics = "0.8.1"
embassy-executor = { version = "0.9.1", features = ["arch-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-stm32-fsmc-display-interface = "0.2"
embedded-aht20 = { version ="0.2", path = "../embedded-aht20" }
heapless = "0.8"

crc = "3.2"

[features]
default = ["stm32f407vg"]
stm32f407vg = ["embassy-stm32/stm32f407vg"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = 2

[profile.dev]
opt-level = 0
debug = 2
